// Code generated by go-swagger; DO NOT EDIT.

package installedapps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// DeleteInstallationReader is a Reader for the DeleteInstallation structure.
type DeleteInstallationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInstallationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteInstallationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInstallationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteInstallationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteInstallationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteInstallationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteInstallationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteInstallationOK creates a DeleteInstallationOK with default headers values
func NewDeleteInstallationOK() *DeleteInstallationOK {
	return &DeleteInstallationOK{}
}

/*DeleteInstallationOK handles this case with default header values.

The number of installed apps deleted.
*/
type DeleteInstallationOK struct {
	Payload *models.DeleteInstalledAppResponse
}

func (o *DeleteInstallationOK) Error() string {
	return fmt.Sprintf("[DELETE /installedapps/{installedAppId}][%d] deleteInstallationOK  %+v", 200, o.Payload)
}

func (o *DeleteInstallationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteInstalledAppResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteInstallationBadRequest creates a DeleteInstallationBadRequest with default headers values
func NewDeleteInstallationBadRequest() *DeleteInstallationBadRequest {
	return &DeleteInstallationBadRequest{}
}

/*DeleteInstallationBadRequest handles this case with default header values.

Bad request
*/
type DeleteInstallationBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteInstallationBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /installedapps/{installedAppId}][%d] deleteInstallationBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteInstallationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteInstallationUnauthorized creates a DeleteInstallationUnauthorized with default headers values
func NewDeleteInstallationUnauthorized() *DeleteInstallationUnauthorized {
	return &DeleteInstallationUnauthorized{}
}

/*DeleteInstallationUnauthorized handles this case with default header values.

Not authenticated
*/
type DeleteInstallationUnauthorized struct {
}

func (o *DeleteInstallationUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /installedapps/{installedAppId}][%d] deleteInstallationUnauthorized ", 401)
}

func (o *DeleteInstallationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstallationForbidden creates a DeleteInstallationForbidden with default headers values
func NewDeleteInstallationForbidden() *DeleteInstallationForbidden {
	return &DeleteInstallationForbidden{}
}

/*DeleteInstallationForbidden handles this case with default header values.

Not authorized
*/
type DeleteInstallationForbidden struct {
}

func (o *DeleteInstallationForbidden) Error() string {
	return fmt.Sprintf("[DELETE /installedapps/{installedAppId}][%d] deleteInstallationForbidden ", 403)
}

func (o *DeleteInstallationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstallationTooManyRequests creates a DeleteInstallationTooManyRequests with default headers values
func NewDeleteInstallationTooManyRequests() *DeleteInstallationTooManyRequests {
	return &DeleteInstallationTooManyRequests{}
}

/*DeleteInstallationTooManyRequests handles this case with default header values.

Too many requests
*/
type DeleteInstallationTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *DeleteInstallationTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /installedapps/{installedAppId}][%d] deleteInstallationTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeleteInstallationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteInstallationDefault creates a DeleteInstallationDefault with default headers values
func NewDeleteInstallationDefault(code int) *DeleteInstallationDefault {
	return &DeleteInstallationDefault{
		_statusCode: code,
	}
}

/*DeleteInstallationDefault handles this case with default header values.

Unexpected error
*/
type DeleteInstallationDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete installation default response
func (o *DeleteInstallationDefault) Code() int {
	return o._statusCode
}

func (o *DeleteInstallationDefault) Error() string {
	return fmt.Sprintf("[DELETE /installedapps/{installedAppId}][%d] deleteInstallation default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteInstallationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
