// Code generated by go-swagger; DO NOT EDIT.

package installedapps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// ListInstallationConfigReader is a Reader for the ListInstallationConfig structure.
type ListInstallationConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInstallationConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListInstallationConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewListInstallationConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewListInstallationConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewListInstallationConfigForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewListInstallationConfigTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewListInstallationConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListInstallationConfigOK creates a ListInstallationConfigOK with default headers values
func NewListInstallationConfigOK() *ListInstallationConfigOK {
	return &ListInstallationConfigOK{}
}

/*ListInstallationConfigOK handles this case with default header values.

An paginated list of install configuration.
*/
type ListInstallationConfigOK struct {
	Payload *models.PagedInstallConfigurations
}

func (o *ListInstallationConfigOK) Error() string {
	return fmt.Sprintf("[GET /installedapps/{installedAppId}/configs][%d] listInstallationConfigOK  %+v", 200, o.Payload)
}

func (o *ListInstallationConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedInstallConfigurations)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstallationConfigBadRequest creates a ListInstallationConfigBadRequest with default headers values
func NewListInstallationConfigBadRequest() *ListInstallationConfigBadRequest {
	return &ListInstallationConfigBadRequest{}
}

/*ListInstallationConfigBadRequest handles this case with default header values.

Bad request
*/
type ListInstallationConfigBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *ListInstallationConfigBadRequest) Error() string {
	return fmt.Sprintf("[GET /installedapps/{installedAppId}/configs][%d] listInstallationConfigBadRequest  %+v", 400, o.Payload)
}

func (o *ListInstallationConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstallationConfigUnauthorized creates a ListInstallationConfigUnauthorized with default headers values
func NewListInstallationConfigUnauthorized() *ListInstallationConfigUnauthorized {
	return &ListInstallationConfigUnauthorized{}
}

/*ListInstallationConfigUnauthorized handles this case with default header values.

Not authenticated
*/
type ListInstallationConfigUnauthorized struct {
}

func (o *ListInstallationConfigUnauthorized) Error() string {
	return fmt.Sprintf("[GET /installedapps/{installedAppId}/configs][%d] listInstallationConfigUnauthorized ", 401)
}

func (o *ListInstallationConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstallationConfigForbidden creates a ListInstallationConfigForbidden with default headers values
func NewListInstallationConfigForbidden() *ListInstallationConfigForbidden {
	return &ListInstallationConfigForbidden{}
}

/*ListInstallationConfigForbidden handles this case with default header values.

Not authorized
*/
type ListInstallationConfigForbidden struct {
}

func (o *ListInstallationConfigForbidden) Error() string {
	return fmt.Sprintf("[GET /installedapps/{installedAppId}/configs][%d] listInstallationConfigForbidden ", 403)
}

func (o *ListInstallationConfigForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstallationConfigTooManyRequests creates a ListInstallationConfigTooManyRequests with default headers values
func NewListInstallationConfigTooManyRequests() *ListInstallationConfigTooManyRequests {
	return &ListInstallationConfigTooManyRequests{}
}

/*ListInstallationConfigTooManyRequests handles this case with default header values.

Too many requests
*/
type ListInstallationConfigTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *ListInstallationConfigTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /installedapps/{installedAppId}/configs][%d] listInstallationConfigTooManyRequests  %+v", 429, o.Payload)
}

func (o *ListInstallationConfigTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstallationConfigDefault creates a ListInstallationConfigDefault with default headers values
func NewListInstallationConfigDefault(code int) *ListInstallationConfigDefault {
	return &ListInstallationConfigDefault{
		_statusCode: code,
	}
}

/*ListInstallationConfigDefault handles this case with default header values.

Unexpected error
*/
type ListInstallationConfigDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list installation config default response
func (o *ListInstallationConfigDefault) Code() int {
	return o._statusCode
}

func (o *ListInstallationConfigDefault) Error() string {
	return fmt.Sprintf("[GET /installedapps/{installedAppId}/configs][%d] listInstallationConfig default  %+v", o._statusCode, o.Payload)
}

func (o *ListInstallationConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
