// Code generated by go-swagger; DO NOT EDIT.

package installedapps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// ListInstallationsReader is a Reader for the ListInstallations structure.
type ListInstallationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInstallationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListInstallationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewListInstallationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewListInstallationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewListInstallationsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewListInstallationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListInstallationsOK creates a ListInstallationsOK with default headers values
func NewListInstallationsOK() *ListInstallationsOK {
	return &ListInstallationsOK{}
}

/*ListInstallationsOK handles this case with default header values.

A paginated list of installed apps.
*/
type ListInstallationsOK struct {
	Payload *models.PagedInstalledApps
}

func (o *ListInstallationsOK) Error() string {
	return fmt.Sprintf("[GET /installedapps][%d] listInstallationsOK  %+v", 200, o.Payload)
}

func (o *ListInstallationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedInstalledApps)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstallationsUnauthorized creates a ListInstallationsUnauthorized with default headers values
func NewListInstallationsUnauthorized() *ListInstallationsUnauthorized {
	return &ListInstallationsUnauthorized{}
}

/*ListInstallationsUnauthorized handles this case with default header values.

Not authenticated
*/
type ListInstallationsUnauthorized struct {
}

func (o *ListInstallationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /installedapps][%d] listInstallationsUnauthorized ", 401)
}

func (o *ListInstallationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstallationsForbidden creates a ListInstallationsForbidden with default headers values
func NewListInstallationsForbidden() *ListInstallationsForbidden {
	return &ListInstallationsForbidden{}
}

/*ListInstallationsForbidden handles this case with default header values.

Not authorized
*/
type ListInstallationsForbidden struct {
}

func (o *ListInstallationsForbidden) Error() string {
	return fmt.Sprintf("[GET /installedapps][%d] listInstallationsForbidden ", 403)
}

func (o *ListInstallationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstallationsTooManyRequests creates a ListInstallationsTooManyRequests with default headers values
func NewListInstallationsTooManyRequests() *ListInstallationsTooManyRequests {
	return &ListInstallationsTooManyRequests{}
}

/*ListInstallationsTooManyRequests handles this case with default header values.

Too many requests
*/
type ListInstallationsTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *ListInstallationsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /installedapps][%d] listInstallationsTooManyRequests  %+v", 429, o.Payload)
}

func (o *ListInstallationsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstallationsDefault creates a ListInstallationsDefault with default headers values
func NewListInstallationsDefault(code int) *ListInstallationsDefault {
	return &ListInstallationsDefault{
		_statusCode: code,
	}
}

/*ListInstallationsDefault handles this case with default header values.

Unexpected error
*/
type ListInstallationsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list installations default response
func (o *ListInstallationsDefault) Code() int {
	return o._statusCode
}

func (o *ListInstallationsDefault) Error() string {
	return fmt.Sprintf("[GET /installedapps][%d] listInstallations default  %+v", o._statusCode, o.Payload)
}

func (o *ListInstallationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
