// Code generated by go-swagger; DO NOT EDIT.

package installedapps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// NewPatchInstalledAppTagsParams creates a new PatchInstalledAppTagsParams object
// with the default values initialized.
func NewPatchInstalledAppTagsParams() *PatchInstalledAppTagsParams {
	var ()
	return &PatchInstalledAppTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchInstalledAppTagsParamsWithTimeout creates a new PatchInstalledAppTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchInstalledAppTagsParamsWithTimeout(timeout time.Duration) *PatchInstalledAppTagsParams {
	var ()
	return &PatchInstalledAppTagsParams{

		timeout: timeout,
	}
}

// NewPatchInstalledAppTagsParamsWithContext creates a new PatchInstalledAppTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchInstalledAppTagsParamsWithContext(ctx context.Context) *PatchInstalledAppTagsParams {
	var ()
	return &PatchInstalledAppTagsParams{

		Context: ctx,
	}
}

// NewPatchInstalledAppTagsParamsWithHTTPClient creates a new PatchInstalledAppTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchInstalledAppTagsParamsWithHTTPClient(client *http.Client) *PatchInstalledAppTagsParams {
	var ()
	return &PatchInstalledAppTagsParams{
		HTTPClient: client,
	}
}

/*PatchInstalledAppTagsParams contains all the parameters to send to the API endpoint
for the patch installed app tags operation typically these are written to a http.Request
*/
type PatchInstalledAppTagsParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*InstalledAppID
	  The ID of the installed application.

	*/
	InstalledAppID string
	/*PatchInstalledAppTagsRequest*/
	PatchInstalledAppTagsRequest *models.PatchTagsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) WithTimeout(timeout time.Duration) *PatchInstalledAppTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) WithContext(ctx context.Context) *PatchInstalledAppTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) WithHTTPClient(client *http.Client) *PatchInstalledAppTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) WithAuthorization(authorization string) *PatchInstalledAppTagsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstalledAppID adds the installedAppID to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) WithInstalledAppID(installedAppID string) *PatchInstalledAppTagsParams {
	o.SetInstalledAppID(installedAppID)
	return o
}

// SetInstalledAppID adds the installedAppId to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) SetInstalledAppID(installedAppID string) {
	o.InstalledAppID = installedAppID
}

// WithPatchInstalledAppTagsRequest adds the patchInstalledAppTagsRequest to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) WithPatchInstalledAppTagsRequest(patchInstalledAppTagsRequest *models.PatchTagsRequest) *PatchInstalledAppTagsParams {
	o.SetPatchInstalledAppTagsRequest(patchInstalledAppTagsRequest)
	return o
}

// SetPatchInstalledAppTagsRequest adds the patchInstalledAppTagsRequest to the patch installed app tags params
func (o *PatchInstalledAppTagsParams) SetPatchInstalledAppTagsRequest(patchInstalledAppTagsRequest *models.PatchTagsRequest) {
	o.PatchInstalledAppTagsRequest = patchInstalledAppTagsRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PatchInstalledAppTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param installedAppId
	if err := r.SetPathParam("installedAppId", o.InstalledAppID); err != nil {
		return err
	}

	if o.PatchInstalledAppTagsRequest != nil {
		if err := r.SetBodyParam(o.PatchInstalledAppTagsRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
