// Code generated by go-swagger; DO NOT EDIT.

package installedapps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// NewUpdateInstalledAppTagsParams creates a new UpdateInstalledAppTagsParams object
// with the default values initialized.
func NewUpdateInstalledAppTagsParams() *UpdateInstalledAppTagsParams {
	var ()
	return &UpdateInstalledAppTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateInstalledAppTagsParamsWithTimeout creates a new UpdateInstalledAppTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateInstalledAppTagsParamsWithTimeout(timeout time.Duration) *UpdateInstalledAppTagsParams {
	var ()
	return &UpdateInstalledAppTagsParams{

		timeout: timeout,
	}
}

// NewUpdateInstalledAppTagsParamsWithContext creates a new UpdateInstalledAppTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateInstalledAppTagsParamsWithContext(ctx context.Context) *UpdateInstalledAppTagsParams {
	var ()
	return &UpdateInstalledAppTagsParams{

		Context: ctx,
	}
}

// NewUpdateInstalledAppTagsParamsWithHTTPClient creates a new UpdateInstalledAppTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateInstalledAppTagsParamsWithHTTPClient(client *http.Client) *UpdateInstalledAppTagsParams {
	var ()
	return &UpdateInstalledAppTagsParams{
		HTTPClient: client,
	}
}

/*UpdateInstalledAppTagsParams contains all the parameters to send to the API endpoint
for the update installed app tags operation typically these are written to a http.Request
*/
type UpdateInstalledAppTagsParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*InstalledAppID
	  The ID of the installed application.

	*/
	InstalledAppID string
	/*UpdateInstalledAppTagsRequest*/
	UpdateInstalledAppTagsRequest *models.UpdateTagsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) WithTimeout(timeout time.Duration) *UpdateInstalledAppTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) WithContext(ctx context.Context) *UpdateInstalledAppTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) WithHTTPClient(client *http.Client) *UpdateInstalledAppTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) WithAuthorization(authorization string) *UpdateInstalledAppTagsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstalledAppID adds the installedAppID to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) WithInstalledAppID(installedAppID string) *UpdateInstalledAppTagsParams {
	o.SetInstalledAppID(installedAppID)
	return o
}

// SetInstalledAppID adds the installedAppId to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) SetInstalledAppID(installedAppID string) {
	o.InstalledAppID = installedAppID
}

// WithUpdateInstalledAppTagsRequest adds the updateInstalledAppTagsRequest to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) WithUpdateInstalledAppTagsRequest(updateInstalledAppTagsRequest *models.UpdateTagsRequest) *UpdateInstalledAppTagsParams {
	o.SetUpdateInstalledAppTagsRequest(updateInstalledAppTagsRequest)
	return o
}

// SetUpdateInstalledAppTagsRequest adds the updateInstalledAppTagsRequest to the update installed app tags params
func (o *UpdateInstalledAppTagsParams) SetUpdateInstalledAppTagsRequest(updateInstalledAppTagsRequest *models.UpdateTagsRequest) {
	o.UpdateInstalledAppTagsRequest = updateInstalledAppTagsRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateInstalledAppTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param installedAppId
	if err := r.SetPathParam("installedAppId", o.InstalledAppID); err != nil {
		return err
	}

	if o.UpdateInstalledAppTagsRequest != nil {
		if err := r.SetBodyParam(o.UpdateInstalledAppTagsRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
