// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// CreateLocationReader is a Reader for the CreateLocation structure.
type CreateLocationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateLocationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateLocationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateLocationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateLocationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateLocationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewCreateLocationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewCreateLocationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCreateLocationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateLocationOK creates a CreateLocationOK with default headers values
func NewCreateLocationOK() *CreateLocationOK {
	return &CreateLocationOK{}
}

/*CreateLocationOK handles this case with default header values.

Created successfully.
*/
type CreateLocationOK struct {
	Payload *models.Location
}

func (o *CreateLocationOK) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocationOK  %+v", 200, o.Payload)
}

func (o *CreateLocationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Location)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateLocationBadRequest creates a CreateLocationBadRequest with default headers values
func NewCreateLocationBadRequest() *CreateLocationBadRequest {
	return &CreateLocationBadRequest{}
}

/*CreateLocationBadRequest handles this case with default header values.

Bad request
*/
type CreateLocationBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *CreateLocationBadRequest) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocationBadRequest  %+v", 400, o.Payload)
}

func (o *CreateLocationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateLocationUnauthorized creates a CreateLocationUnauthorized with default headers values
func NewCreateLocationUnauthorized() *CreateLocationUnauthorized {
	return &CreateLocationUnauthorized{}
}

/*CreateLocationUnauthorized handles this case with default header values.

Not authenticated
*/
type CreateLocationUnauthorized struct {
}

func (o *CreateLocationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocationUnauthorized ", 401)
}

func (o *CreateLocationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateLocationForbidden creates a CreateLocationForbidden with default headers values
func NewCreateLocationForbidden() *CreateLocationForbidden {
	return &CreateLocationForbidden{}
}

/*CreateLocationForbidden handles this case with default header values.

Not authorized
*/
type CreateLocationForbidden struct {
}

func (o *CreateLocationForbidden) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocationForbidden ", 403)
}

func (o *CreateLocationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateLocationUnprocessableEntity creates a CreateLocationUnprocessableEntity with default headers values
func NewCreateLocationUnprocessableEntity() *CreateLocationUnprocessableEntity {
	return &CreateLocationUnprocessableEntity{}
}

/*CreateLocationUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type CreateLocationUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

func (o *CreateLocationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocationUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateLocationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateLocationTooManyRequests creates a CreateLocationTooManyRequests with default headers values
func NewCreateLocationTooManyRequests() *CreateLocationTooManyRequests {
	return &CreateLocationTooManyRequests{}
}

/*CreateLocationTooManyRequests handles this case with default header values.

Too many requests
*/
type CreateLocationTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *CreateLocationTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocationTooManyRequests  %+v", 429, o.Payload)
}

func (o *CreateLocationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateLocationDefault creates a CreateLocationDefault with default headers values
func NewCreateLocationDefault(code int) *CreateLocationDefault {
	return &CreateLocationDefault{
		_statusCode: code,
	}
}

/*CreateLocationDefault handles this case with default header values.

Unexpected error
*/
type CreateLocationDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the create location default response
func (o *CreateLocationDefault) Code() int {
	return o._statusCode
}

func (o *CreateLocationDefault) Error() string {
	return fmt.Sprintf("[POST /locations][%d] createLocation default  %+v", o._statusCode, o.Payload)
}

func (o *CreateLocationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
