// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// DeleteLocationReader is a Reader for the DeleteLocation structure.
type DeleteLocationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLocationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteLocationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteLocationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteLocationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteLocationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteLocationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteLocationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteLocationOK creates a DeleteLocationOK with default headers values
func NewDeleteLocationOK() *DeleteLocationOK {
	return &DeleteLocationOK{}
}

/*DeleteLocationOK handles this case with default header values.

An empty object response.
*/
type DeleteLocationOK struct {
	Payload models.DeleteLocationResponse
}

func (o *DeleteLocationOK) Error() string {
	return fmt.Sprintf("[DELETE /locations/{locationId}][%d] deleteLocationOK  %+v", 200, o.Payload)
}

func (o *DeleteLocationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLocationBadRequest creates a DeleteLocationBadRequest with default headers values
func NewDeleteLocationBadRequest() *DeleteLocationBadRequest {
	return &DeleteLocationBadRequest{}
}

/*DeleteLocationBadRequest handles this case with default header values.

Bad request
*/
type DeleteLocationBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteLocationBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /locations/{locationId}][%d] deleteLocationBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteLocationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLocationUnauthorized creates a DeleteLocationUnauthorized with default headers values
func NewDeleteLocationUnauthorized() *DeleteLocationUnauthorized {
	return &DeleteLocationUnauthorized{}
}

/*DeleteLocationUnauthorized handles this case with default header values.

Not authenticated
*/
type DeleteLocationUnauthorized struct {
}

func (o *DeleteLocationUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /locations/{locationId}][%d] deleteLocationUnauthorized ", 401)
}

func (o *DeleteLocationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLocationForbidden creates a DeleteLocationForbidden with default headers values
func NewDeleteLocationForbidden() *DeleteLocationForbidden {
	return &DeleteLocationForbidden{}
}

/*DeleteLocationForbidden handles this case with default header values.

Not authorized
*/
type DeleteLocationForbidden struct {
}

func (o *DeleteLocationForbidden) Error() string {
	return fmt.Sprintf("[DELETE /locations/{locationId}][%d] deleteLocationForbidden ", 403)
}

func (o *DeleteLocationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLocationTooManyRequests creates a DeleteLocationTooManyRequests with default headers values
func NewDeleteLocationTooManyRequests() *DeleteLocationTooManyRequests {
	return &DeleteLocationTooManyRequests{}
}

/*DeleteLocationTooManyRequests handles this case with default header values.

Too many requests
*/
type DeleteLocationTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *DeleteLocationTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /locations/{locationId}][%d] deleteLocationTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeleteLocationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLocationDefault creates a DeleteLocationDefault with default headers values
func NewDeleteLocationDefault(code int) *DeleteLocationDefault {
	return &DeleteLocationDefault{
		_statusCode: code,
	}
}

/*DeleteLocationDefault handles this case with default header values.

Unexpected error
*/
type DeleteLocationDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete location default response
func (o *DeleteLocationDefault) Code() int {
	return o._statusCode
}

func (o *DeleteLocationDefault) Error() string {
	return fmt.Sprintf("[DELETE /locations/{locationId}][%d] deleteLocation default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteLocationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
