// Code generated by go-swagger; DO NOT EDIT.

package modes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// NewChangeModeParams creates a new ChangeModeParams object
// with the default values initialized.
func NewChangeModeParams() *ChangeModeParams {
	var ()
	return &ChangeModeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeModeParamsWithTimeout creates a new ChangeModeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeModeParamsWithTimeout(timeout time.Duration) *ChangeModeParams {
	var ()
	return &ChangeModeParams{

		timeout: timeout,
	}
}

// NewChangeModeParamsWithContext creates a new ChangeModeParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeModeParamsWithContext(ctx context.Context) *ChangeModeParams {
	var ()
	return &ChangeModeParams{

		Context: ctx,
	}
}

// NewChangeModeParamsWithHTTPClient creates a new ChangeModeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeModeParamsWithHTTPClient(client *http.Client) *ChangeModeParams {
	var ()
	return &ChangeModeParams{
		HTTPClient: client,
	}
}

/*ChangeModeParams contains all the parameters to send to the API endpoint
for the change mode operation typically these are written to a http.Request
*/
type ChangeModeParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*ChangeModeRequest*/
	ChangeModeRequest *models.ChangeModeRequest
	/*LocationID
	  The ID of the location.

	*/
	LocationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change mode params
func (o *ChangeModeParams) WithTimeout(timeout time.Duration) *ChangeModeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change mode params
func (o *ChangeModeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change mode params
func (o *ChangeModeParams) WithContext(ctx context.Context) *ChangeModeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change mode params
func (o *ChangeModeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change mode params
func (o *ChangeModeParams) WithHTTPClient(client *http.Client) *ChangeModeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change mode params
func (o *ChangeModeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the change mode params
func (o *ChangeModeParams) WithAuthorization(authorization string) *ChangeModeParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the change mode params
func (o *ChangeModeParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithChangeModeRequest adds the changeModeRequest to the change mode params
func (o *ChangeModeParams) WithChangeModeRequest(changeModeRequest *models.ChangeModeRequest) *ChangeModeParams {
	o.SetChangeModeRequest(changeModeRequest)
	return o
}

// SetChangeModeRequest adds the changeModeRequest to the change mode params
func (o *ChangeModeParams) SetChangeModeRequest(changeModeRequest *models.ChangeModeRequest) {
	o.ChangeModeRequest = changeModeRequest
}

// WithLocationID adds the locationID to the change mode params
func (o *ChangeModeParams) WithLocationID(locationID string) *ChangeModeParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the change mode params
func (o *ChangeModeParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeModeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.ChangeModeRequest != nil {
		if err := r.SetBodyParam(o.ChangeModeRequest); err != nil {
			return err
		}
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
