// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DashboardCardLifecycle dashboard card lifecycle
// swagger:model DashboardCardLifecycle
type DashboardCardLifecycle string

const (

	// DashboardCardLifecycleUPDATE captures enum value "UPDATE"
	DashboardCardLifecycleUPDATE DashboardCardLifecycle = "UPDATE"

	// DashboardCardLifecycleDELETE captures enum value "DELETE"
	DashboardCardLifecycleDELETE DashboardCardLifecycle = "DELETE"
)

// for schema
var dashboardCardLifecycleEnum []interface{}

func init() {
	var res []DashboardCardLifecycle
	if err := json.Unmarshal([]byte(`["UPDATE","DELETE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dashboardCardLifecycleEnum = append(dashboardCardLifecycleEnum, v)
	}
}

func (m DashboardCardLifecycle) validateDashboardCardLifecycleEnum(path, location string, value DashboardCardLifecycle) error {
	if err := validate.Enum(path, location, value, dashboardCardLifecycleEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this dashboard card lifecycle
func (m DashboardCardLifecycle) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDashboardCardLifecycleEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
