// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DeviceProfileReference device profile reference
// swagger:model DeviceProfileReference
type DeviceProfileReference struct {

	// The device profile Id
	ID string `json:"id,omitempty"`
}

// Validate validates this device profile reference
func (m *DeviceProfileReference) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceProfileReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceProfileReference) UnmarshalBinary(b []byte) error {
	var res DeviceProfileReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
