// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetAppSettingsResponse Settings for a given app
// swagger:model GetAppSettingsResponse
type GetAppSettingsResponse struct {

	// settings
	Settings map[string]string `json:"settings,omitempty"`
}

// Validate validates this get app settings response
func (m *GetAppSettingsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAppSettingsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAppSettingsResponse) UnmarshalBinary(b []byte) error {
	var res GetAppSettingsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
