// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SubscriptionDelete The number of deleted subscriptions
// swagger:model SubscriptionDelete
type SubscriptionDelete struct {

	// count
	Count int32 `json:"count,omitempty"`
}

// Validate validates this subscription delete
func (m *SubscriptionDelete) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionDelete) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionDelete) UnmarshalBinary(b []byte) error {
	var res SubscriptionDelete
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
