// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Tags A map of user-defined tags which can be used to associate arbitrary metadata to a resource, and can be
// useful for filtering.
//
// * Key length must be between 1 and 64 (inclusive) Unicode characters in UTF-8
// * Value length must be between 1 and 256 (inclusive) Unicode characters in UTF-8
// * Case sensitive
// * Maximum number of tags per resource: 25
// * Reserved prefix — `st:`
// * ST-generated tag names and values are automatically assigned the `st:` prefix, which you cannot assign.
// * Use each key only once for each resource. If you attempt to use the same key twice on the same resource the last key wins.
// * You cannot tag a resource at the same time you create it. Tagging requires a separate action after the resource is created.
// * Allowed characters for *keys* are letters, plus the following special characters: `:`, `_`
// * Allowed characters for *values* are letters, whitespace, and numbers, plus the following special characters: `+`, `-`, `=`, `.`, `_`, `:`, `/`
// * If you need characters outside this allowed set, you can apply standard base-64 encoding to your tag.
//
// swagger:model Tags
type Tags map[string]string

// Validate validates this tags
func (m Tags) Validate(formats strfmt.Registry) error {
	return nil
}
