// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DashboardCardTemplate A directive to the SmartThings client to use a specific template for rendering the dashboard card.
// Each card template may have a different set requirement for data needs.
//
// * BASIC_V1 - The basic / default template.
// * FREE_FORM - A free form template with minimal constraints.
//
// swagger:model DashboardCardTemplate
type DashboardCardTemplate string

const (

	// DashboardCardTemplateBASICV1 captures enum value "BASIC_V1"
	DashboardCardTemplateBASICV1 DashboardCardTemplate = "BASIC_V1"

	// DashboardCardTemplateFREEFORM captures enum value "FREE_FORM"
	DashboardCardTemplateFREEFORM DashboardCardTemplate = "FREE_FORM"
)

// for schema
var dashboardCardTemplateEnum []interface{}

func init() {
	var res []DashboardCardTemplate
	if err := json.Unmarshal([]byte(`["BASIC_V1","FREE_FORM"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dashboardCardTemplateEnum = append(dashboardCardTemplateEnum, v)
	}
}

func (m DashboardCardTemplate) validateDashboardCardTemplateEnum(path, location string, value DashboardCardTemplate) error {
	if err := validate.Enum(path, location, value, dashboardCardTemplateEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this dashboard card template
func (m DashboardCardTemplate) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDashboardCardTemplateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
