// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DeviceLifecycleDelete Delete device lifecycle.
//
// swagger:model DeviceLifecycleDelete
type DeviceLifecycleDelete interface{}
