// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// EventResponseData Empty object response for an Event lifecycle execution.
//
// swagger:model EventResponseData
type EventResponseData interface{}
