// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ExecuteAction Call the EXECUTE lifecycle on the backing SmartApp.
// swagger:model ExecuteAction
type ExecuteAction struct {

	// An arbitrary map of input parameters which the SmartApp can use to build a custom response.
	Parameters map[string]string `json:"parameters,omitempty"`
}

// Validate validates this execute action
func (m *ExecuteAction) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExecuteAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExecuteAction) UnmarshalBinary(b []byte) error {
	var res ExecuteAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
