// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OAuthCallbackResponseData Empty object response for an OAuth Callback lifecycle execution.
//
// swagger:model OAuthCallbackResponseData
type OAuthCallbackResponseData interface{}
