// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OAuthCallbackData Provides intergration with the result of a third party oauth attempt.  This will only be available for executions of type "OAUTH_CALLBACK".
//
// swagger:model OAuthCallbackData
type OAuthCallbackData struct {

	// The id of the installed app.
	InstalledAppID string `json:"installedAppId,omitempty"`

	// A relative URL containing all of the query string parameters as returned by the third party oauth system. A SmartApp can
	// parse the `urlPath` property to extract any senstive auth codes/tokens which can then be used to access the third party system.
	//
	URLPath string `json:"urlPath,omitempty"`
}

// Validate validates this o auth callback data
func (m *OAuthCallbackData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OAuthCallbackData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OAuthCallbackData) UnmarshalBinary(b []byte) error {
	var res OAuthCallbackData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
