// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PingData A request to ping a SmartApp to ensure connectivity.
//
// swagger:model PingData
type PingData struct {

	// A challenge phrase that the SmartApp must echo back to validate itself.
	// Required: true
	Challenge *string `json:"challenge"`
}

// Validate validates this ping data
func (m *PingData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChallenge(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PingData) validateChallenge(formats strfmt.Registry) error {

	if err := validate.Required("challenge", "body", m.Challenge); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PingData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PingData) UnmarshalBinary(b []byte) error {
	var res PingData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
