// Code generated by go-swagger; DO NOT EDIT.

package smartapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TimerType The type of TIMER_EVENT.
// swagger:model TimerType
type TimerType string

const (

	// TimerTypeCRON captures enum value "CRON"
	TimerTypeCRON TimerType = "CRON"

	// TimerTypeONCE captures enum value "ONCE"
	TimerTypeONCE TimerType = "ONCE"
)

// for schema
var timerTypeEnum []interface{}

func init() {
	var res []TimerType
	if err := json.Unmarshal([]byte(`["CRON","ONCE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		timerTypeEnum = append(timerTypeEnum, v)
	}
}

func (m TimerType) validateTimerTypeEnum(path, location string, value TimerType) error {
	if err := validate.Enum(path, location, value, timerTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this timer type
func (m TimerType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTimerTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
