// Code generated by go-swagger; DO NOT EDIT.

package deviceprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// CreateDeviceProfileReader is a Reader for the CreateDeviceProfile structure.
type CreateDeviceProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDeviceProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateDeviceProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateDeviceProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateDeviceProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateDeviceProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewCreateDeviceProfileTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCreateDeviceProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateDeviceProfileOK creates a CreateDeviceProfileOK with default headers values
func NewCreateDeviceProfileOK() *CreateDeviceProfileOK {
	return &CreateDeviceProfileOK{}
}

/*CreateDeviceProfileOK handles this case with default header values.

The device profile
*/
type CreateDeviceProfileOK struct {
	Payload *models.DeviceProfile
}

func (o *CreateDeviceProfileOK) Error() string {
	return fmt.Sprintf("[POST /deviceprofiles][%d] createDeviceProfileOK  %+v", 200, o.Payload)
}

func (o *CreateDeviceProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDeviceProfileBadRequest creates a CreateDeviceProfileBadRequest with default headers values
func NewCreateDeviceProfileBadRequest() *CreateDeviceProfileBadRequest {
	return &CreateDeviceProfileBadRequest{}
}

/*CreateDeviceProfileBadRequest handles this case with default header values.

Bad request
*/
type CreateDeviceProfileBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *CreateDeviceProfileBadRequest) Error() string {
	return fmt.Sprintf("[POST /deviceprofiles][%d] createDeviceProfileBadRequest  %+v", 400, o.Payload)
}

func (o *CreateDeviceProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDeviceProfileUnauthorized creates a CreateDeviceProfileUnauthorized with default headers values
func NewCreateDeviceProfileUnauthorized() *CreateDeviceProfileUnauthorized {
	return &CreateDeviceProfileUnauthorized{}
}

/*CreateDeviceProfileUnauthorized handles this case with default header values.

Not authenticated
*/
type CreateDeviceProfileUnauthorized struct {
}

func (o *CreateDeviceProfileUnauthorized) Error() string {
	return fmt.Sprintf("[POST /deviceprofiles][%d] createDeviceProfileUnauthorized ", 401)
}

func (o *CreateDeviceProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDeviceProfileForbidden creates a CreateDeviceProfileForbidden with default headers values
func NewCreateDeviceProfileForbidden() *CreateDeviceProfileForbidden {
	return &CreateDeviceProfileForbidden{}
}

/*CreateDeviceProfileForbidden handles this case with default header values.

Not authorized
*/
type CreateDeviceProfileForbidden struct {
}

func (o *CreateDeviceProfileForbidden) Error() string {
	return fmt.Sprintf("[POST /deviceprofiles][%d] createDeviceProfileForbidden ", 403)
}

func (o *CreateDeviceProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDeviceProfileTooManyRequests creates a CreateDeviceProfileTooManyRequests with default headers values
func NewCreateDeviceProfileTooManyRequests() *CreateDeviceProfileTooManyRequests {
	return &CreateDeviceProfileTooManyRequests{}
}

/*CreateDeviceProfileTooManyRequests handles this case with default header values.

Too many requests
*/
type CreateDeviceProfileTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *CreateDeviceProfileTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /deviceprofiles][%d] createDeviceProfileTooManyRequests  %+v", 429, o.Payload)
}

func (o *CreateDeviceProfileTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDeviceProfileDefault creates a CreateDeviceProfileDefault with default headers values
func NewCreateDeviceProfileDefault(code int) *CreateDeviceProfileDefault {
	return &CreateDeviceProfileDefault{
		_statusCode: code,
	}
}

/*CreateDeviceProfileDefault handles this case with default header values.

Unexpected error
*/
type CreateDeviceProfileDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the create device profile default response
func (o *CreateDeviceProfileDefault) Code() int {
	return o._statusCode
}

func (o *CreateDeviceProfileDefault) Error() string {
	return fmt.Sprintf("[POST /deviceprofiles][%d] createDeviceProfile default  %+v", o._statusCode, o.Payload)
}

func (o *CreateDeviceProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
