// Code generated by go-swagger; DO NOT EDIT.

package deviceprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// DeleteDeviceProfileTranslationsReader is a Reader for the DeleteDeviceProfileTranslations structure.
type DeleteDeviceProfileTranslationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDeviceProfileTranslationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDeviceProfileTranslationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteDeviceProfileTranslationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteDeviceProfileTranslationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteDeviceProfileTranslationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteDeviceProfileTranslationsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteDeviceProfileTranslationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDeviceProfileTranslationsOK creates a DeleteDeviceProfileTranslationsOK with default headers values
func NewDeleteDeviceProfileTranslationsOK() *DeleteDeviceProfileTranslationsOK {
	return &DeleteDeviceProfileTranslationsOK{}
}

/*DeleteDeviceProfileTranslationsOK handles this case with default header values.

Locale deleted.
*/
type DeleteDeviceProfileTranslationsOK struct {
	Payload interface{}
}

func (o *DeleteDeviceProfileTranslationsOK) Error() string {
	return fmt.Sprintf("[DELETE /deviceprofiles/{deviceProfileId}/i18n/{locale}][%d] deleteDeviceProfileTranslationsOK  %+v", 200, o.Payload)
}

func (o *DeleteDeviceProfileTranslationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeviceProfileTranslationsBadRequest creates a DeleteDeviceProfileTranslationsBadRequest with default headers values
func NewDeleteDeviceProfileTranslationsBadRequest() *DeleteDeviceProfileTranslationsBadRequest {
	return &DeleteDeviceProfileTranslationsBadRequest{}
}

/*DeleteDeviceProfileTranslationsBadRequest handles this case with default header values.

Bad request
*/
type DeleteDeviceProfileTranslationsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteDeviceProfileTranslationsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /deviceprofiles/{deviceProfileId}/i18n/{locale}][%d] deleteDeviceProfileTranslationsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteDeviceProfileTranslationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeviceProfileTranslationsUnauthorized creates a DeleteDeviceProfileTranslationsUnauthorized with default headers values
func NewDeleteDeviceProfileTranslationsUnauthorized() *DeleteDeviceProfileTranslationsUnauthorized {
	return &DeleteDeviceProfileTranslationsUnauthorized{}
}

/*DeleteDeviceProfileTranslationsUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteDeviceProfileTranslationsUnauthorized struct {
}

func (o *DeleteDeviceProfileTranslationsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /deviceprofiles/{deviceProfileId}/i18n/{locale}][%d] deleteDeviceProfileTranslationsUnauthorized ", 401)
}

func (o *DeleteDeviceProfileTranslationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDeviceProfileTranslationsForbidden creates a DeleteDeviceProfileTranslationsForbidden with default headers values
func NewDeleteDeviceProfileTranslationsForbidden() *DeleteDeviceProfileTranslationsForbidden {
	return &DeleteDeviceProfileTranslationsForbidden{}
}

/*DeleteDeviceProfileTranslationsForbidden handles this case with default header values.

Forbidden
*/
type DeleteDeviceProfileTranslationsForbidden struct {
}

func (o *DeleteDeviceProfileTranslationsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /deviceprofiles/{deviceProfileId}/i18n/{locale}][%d] deleteDeviceProfileTranslationsForbidden ", 403)
}

func (o *DeleteDeviceProfileTranslationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDeviceProfileTranslationsTooManyRequests creates a DeleteDeviceProfileTranslationsTooManyRequests with default headers values
func NewDeleteDeviceProfileTranslationsTooManyRequests() *DeleteDeviceProfileTranslationsTooManyRequests {
	return &DeleteDeviceProfileTranslationsTooManyRequests{}
}

/*DeleteDeviceProfileTranslationsTooManyRequests handles this case with default header values.

Too many requests
*/
type DeleteDeviceProfileTranslationsTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *DeleteDeviceProfileTranslationsTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /deviceprofiles/{deviceProfileId}/i18n/{locale}][%d] deleteDeviceProfileTranslationsTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeleteDeviceProfileTranslationsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeviceProfileTranslationsDefault creates a DeleteDeviceProfileTranslationsDefault with default headers values
func NewDeleteDeviceProfileTranslationsDefault(code int) *DeleteDeviceProfileTranslationsDefault {
	return &DeleteDeviceProfileTranslationsDefault{
		_statusCode: code,
	}
}

/*DeleteDeviceProfileTranslationsDefault handles this case with default header values.

Unexpected error
*/
type DeleteDeviceProfileTranslationsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete device profile translations default response
func (o *DeleteDeviceProfileTranslationsDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDeviceProfileTranslationsDefault) Error() string {
	return fmt.Sprintf("[DELETE /deviceprofiles/{deviceProfileId}/i18n/{locale}][%d] deleteDeviceProfileTranslations default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDeviceProfileTranslationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
