// Code generated by go-swagger; DO NOT EDIT.

package deviceprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// UpdateDeviceProfileReader is a Reader for the UpdateDeviceProfile structure.
type UpdateDeviceProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDeviceProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateDeviceProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateDeviceProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewUpdateDeviceProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewUpdateDeviceProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewUpdateDeviceProfileTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewUpdateDeviceProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateDeviceProfileOK creates a UpdateDeviceProfileOK with default headers values
func NewUpdateDeviceProfileOK() *UpdateDeviceProfileOK {
	return &UpdateDeviceProfileOK{}
}

/*UpdateDeviceProfileOK handles this case with default header values.

The device profile
*/
type UpdateDeviceProfileOK struct {
	Payload *models.DeviceProfile
}

func (o *UpdateDeviceProfileOK) Error() string {
	return fmt.Sprintf("[PUT /deviceprofiles/{deviceProfileId}][%d] updateDeviceProfileOK  %+v", 200, o.Payload)
}

func (o *UpdateDeviceProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDeviceProfileBadRequest creates a UpdateDeviceProfileBadRequest with default headers values
func NewUpdateDeviceProfileBadRequest() *UpdateDeviceProfileBadRequest {
	return &UpdateDeviceProfileBadRequest{}
}

/*UpdateDeviceProfileBadRequest handles this case with default header values.

Bad request
*/
type UpdateDeviceProfileBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *UpdateDeviceProfileBadRequest) Error() string {
	return fmt.Sprintf("[PUT /deviceprofiles/{deviceProfileId}][%d] updateDeviceProfileBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateDeviceProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDeviceProfileUnauthorized creates a UpdateDeviceProfileUnauthorized with default headers values
func NewUpdateDeviceProfileUnauthorized() *UpdateDeviceProfileUnauthorized {
	return &UpdateDeviceProfileUnauthorized{}
}

/*UpdateDeviceProfileUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateDeviceProfileUnauthorized struct {
}

func (o *UpdateDeviceProfileUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /deviceprofiles/{deviceProfileId}][%d] updateDeviceProfileUnauthorized ", 401)
}

func (o *UpdateDeviceProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDeviceProfileForbidden creates a UpdateDeviceProfileForbidden with default headers values
func NewUpdateDeviceProfileForbidden() *UpdateDeviceProfileForbidden {
	return &UpdateDeviceProfileForbidden{}
}

/*UpdateDeviceProfileForbidden handles this case with default header values.

Forbidden
*/
type UpdateDeviceProfileForbidden struct {
}

func (o *UpdateDeviceProfileForbidden) Error() string {
	return fmt.Sprintf("[PUT /deviceprofiles/{deviceProfileId}][%d] updateDeviceProfileForbidden ", 403)
}

func (o *UpdateDeviceProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDeviceProfileTooManyRequests creates a UpdateDeviceProfileTooManyRequests with default headers values
func NewUpdateDeviceProfileTooManyRequests() *UpdateDeviceProfileTooManyRequests {
	return &UpdateDeviceProfileTooManyRequests{}
}

/*UpdateDeviceProfileTooManyRequests handles this case with default header values.

Too many requests
*/
type UpdateDeviceProfileTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *UpdateDeviceProfileTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /deviceprofiles/{deviceProfileId}][%d] updateDeviceProfileTooManyRequests  %+v", 429, o.Payload)
}

func (o *UpdateDeviceProfileTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDeviceProfileDefault creates a UpdateDeviceProfileDefault with default headers values
func NewUpdateDeviceProfileDefault(code int) *UpdateDeviceProfileDefault {
	return &UpdateDeviceProfileDefault{
		_statusCode: code,
	}
}

/*UpdateDeviceProfileDefault handles this case with default header values.

Unexpected error
*/
type UpdateDeviceProfileDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the update device profile default response
func (o *UpdateDeviceProfileDefault) Code() int {
	return o._statusCode
}

func (o *UpdateDeviceProfileDefault) Error() string {
	return fmt.Sprintf("[PUT /deviceprofiles/{deviceProfileId}][%d] updateDeviceProfile default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateDeviceProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
