// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAppParams creates a new DeleteAppParams object
// with the default values initialized.
func NewDeleteAppParams() *DeleteAppParams {
	var ()
	return &DeleteAppParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAppParamsWithTimeout creates a new DeleteAppParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAppParamsWithTimeout(timeout time.Duration) *DeleteAppParams {
	var ()
	return &DeleteAppParams{

		timeout: timeout,
	}
}

// NewDeleteAppParamsWithContext creates a new DeleteAppParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAppParamsWithContext(ctx context.Context) *DeleteAppParams {
	var ()
	return &DeleteAppParams{

		Context: ctx,
	}
}

// NewDeleteAppParamsWithHTTPClient creates a new DeleteAppParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAppParamsWithHTTPClient(client *http.Client) *DeleteAppParams {
	var ()
	return &DeleteAppParams{
		HTTPClient: client,
	}
}

/*DeleteAppParams contains all the parameters to send to the API endpoint
for the delete app operation typically these are written to a http.Request
*/
type DeleteAppParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*AppNameOrID
	  The appName or appId field of an app.

	*/
	AppNameOrID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete app params
func (o *DeleteAppParams) WithTimeout(timeout time.Duration) *DeleteAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete app params
func (o *DeleteAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete app params
func (o *DeleteAppParams) WithContext(ctx context.Context) *DeleteAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete app params
func (o *DeleteAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete app params
func (o *DeleteAppParams) WithHTTPClient(client *http.Client) *DeleteAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete app params
func (o *DeleteAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete app params
func (o *DeleteAppParams) WithAuthorization(authorization string) *DeleteAppParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete app params
func (o *DeleteAppParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAppNameOrID adds the appNameOrID to the delete app params
func (o *DeleteAppParams) WithAppNameOrID(appNameOrID string) *DeleteAppParams {
	o.SetAppNameOrID(appNameOrID)
	return o
}

// SetAppNameOrID adds the appNameOrId to the delete app params
func (o *DeleteAppParams) SetAppNameOrID(appNameOrID string) {
	o.AppNameOrID = appNameOrID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param appNameOrId
	if err := r.SetPathParam("appNameOrId", o.AppNameOrID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
