// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAppOauthParams creates a new GetAppOauthParams object
// with the default values initialized.
func NewGetAppOauthParams() *GetAppOauthParams {
	var ()
	return &GetAppOauthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppOauthParamsWithTimeout creates a new GetAppOauthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppOauthParamsWithTimeout(timeout time.Duration) *GetAppOauthParams {
	var ()
	return &GetAppOauthParams{

		timeout: timeout,
	}
}

// NewGetAppOauthParamsWithContext creates a new GetAppOauthParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppOauthParamsWithContext(ctx context.Context) *GetAppOauthParams {
	var ()
	return &GetAppOauthParams{

		Context: ctx,
	}
}

// NewGetAppOauthParamsWithHTTPClient creates a new GetAppOauthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppOauthParamsWithHTTPClient(client *http.Client) *GetAppOauthParams {
	var ()
	return &GetAppOauthParams{
		HTTPClient: client,
	}
}

/*GetAppOauthParams contains all the parameters to send to the API endpoint
for the get app oauth operation typically these are written to a http.Request
*/
type GetAppOauthParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*AppNameOrID
	  The appName or appId field of an app.

	*/
	AppNameOrID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get app oauth params
func (o *GetAppOauthParams) WithTimeout(timeout time.Duration) *GetAppOauthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app oauth params
func (o *GetAppOauthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get app oauth params
func (o *GetAppOauthParams) WithContext(ctx context.Context) *GetAppOauthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app oauth params
func (o *GetAppOauthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get app oauth params
func (o *GetAppOauthParams) WithHTTPClient(client *http.Client) *GetAppOauthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app oauth params
func (o *GetAppOauthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get app oauth params
func (o *GetAppOauthParams) WithAuthorization(authorization string) *GetAppOauthParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get app oauth params
func (o *GetAppOauthParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAppNameOrID adds the appNameOrID to the get app oauth params
func (o *GetAppOauthParams) WithAppNameOrID(appNameOrID string) *GetAppOauthParams {
	o.SetAppNameOrID(appNameOrID)
	return o
}

// SetAppNameOrID adds the appNameOrId to the get app oauth params
func (o *GetAppOauthParams) SetAppNameOrID(appNameOrID string) {
	o.AppNameOrID = appNameOrID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppOauthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param appNameOrId
	if err := r.SetPathParam("appNameOrId", o.AppNameOrID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
