// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// NewUpdateAppTagsParams creates a new UpdateAppTagsParams object
// with the default values initialized.
func NewUpdateAppTagsParams() *UpdateAppTagsParams {
	var ()
	return &UpdateAppTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAppTagsParamsWithTimeout creates a new UpdateAppTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAppTagsParamsWithTimeout(timeout time.Duration) *UpdateAppTagsParams {
	var ()
	return &UpdateAppTagsParams{

		timeout: timeout,
	}
}

// NewUpdateAppTagsParamsWithContext creates a new UpdateAppTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAppTagsParamsWithContext(ctx context.Context) *UpdateAppTagsParams {
	var ()
	return &UpdateAppTagsParams{

		Context: ctx,
	}
}

// NewUpdateAppTagsParamsWithHTTPClient creates a new UpdateAppTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAppTagsParamsWithHTTPClient(client *http.Client) *UpdateAppTagsParams {
	var ()
	return &UpdateAppTagsParams{
		HTTPClient: client,
	}
}

/*UpdateAppTagsParams contains all the parameters to send to the API endpoint
for the update app tags operation typically these are written to a http.Request
*/
type UpdateAppTagsParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*AppNameOrID
	  The appName or appId field of an app.

	*/
	AppNameOrID string
	/*UpdateAppTagsRequest*/
	UpdateAppTagsRequest *models.UpdateTagsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update app tags params
func (o *UpdateAppTagsParams) WithTimeout(timeout time.Duration) *UpdateAppTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update app tags params
func (o *UpdateAppTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update app tags params
func (o *UpdateAppTagsParams) WithContext(ctx context.Context) *UpdateAppTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update app tags params
func (o *UpdateAppTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update app tags params
func (o *UpdateAppTagsParams) WithHTTPClient(client *http.Client) *UpdateAppTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update app tags params
func (o *UpdateAppTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the update app tags params
func (o *UpdateAppTagsParams) WithAuthorization(authorization string) *UpdateAppTagsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the update app tags params
func (o *UpdateAppTagsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAppNameOrID adds the appNameOrID to the update app tags params
func (o *UpdateAppTagsParams) WithAppNameOrID(appNameOrID string) *UpdateAppTagsParams {
	o.SetAppNameOrID(appNameOrID)
	return o
}

// SetAppNameOrID adds the appNameOrId to the update app tags params
func (o *UpdateAppTagsParams) SetAppNameOrID(appNameOrID string) {
	o.AppNameOrID = appNameOrID
}

// WithUpdateAppTagsRequest adds the updateAppTagsRequest to the update app tags params
func (o *UpdateAppTagsParams) WithUpdateAppTagsRequest(updateAppTagsRequest *models.UpdateTagsRequest) *UpdateAppTagsParams {
	o.SetUpdateAppTagsRequest(updateAppTagsRequest)
	return o
}

// SetUpdateAppTagsRequest adds the updateAppTagsRequest to the update app tags params
func (o *UpdateAppTagsParams) SetUpdateAppTagsRequest(updateAppTagsRequest *models.UpdateTagsRequest) {
	o.UpdateAppTagsRequest = updateAppTagsRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAppTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param appNameOrId
	if err := r.SetPathParam("appNameOrId", o.AppNameOrID); err != nil {
		return err
	}

	if o.UpdateAppTagsRequest != nil {
		if err := r.SetBodyParam(o.UpdateAppTagsRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
