// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// UpdateAppTagsReader is a Reader for the UpdateAppTags structure.
type UpdateAppTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAppTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateAppTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateAppTagsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewUpdateAppTagsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewUpdateAppTagsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewUpdateAppTagsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewUpdateAppTagsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewUpdateAppTagsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAppTagsOK creates a UpdateAppTagsOK with default headers values
func NewUpdateAppTagsOK() *UpdateAppTagsOK {
	return &UpdateAppTagsOK{}
}

/*UpdateAppTagsOK handles this case with default header values.

A response containing an App's tags.
*/
type UpdateAppTagsOK struct {
	Payload *models.UpdateTagsResponse
}

func (o *UpdateAppTagsOK) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTagsOK  %+v", 200, o.Payload)
}

func (o *UpdateAppTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateTagsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppTagsBadRequest creates a UpdateAppTagsBadRequest with default headers values
func NewUpdateAppTagsBadRequest() *UpdateAppTagsBadRequest {
	return &UpdateAppTagsBadRequest{}
}

/*UpdateAppTagsBadRequest handles this case with default header values.

Bad request
*/
type UpdateAppTagsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *UpdateAppTagsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTagsBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateAppTagsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppTagsUnauthorized creates a UpdateAppTagsUnauthorized with default headers values
func NewUpdateAppTagsUnauthorized() *UpdateAppTagsUnauthorized {
	return &UpdateAppTagsUnauthorized{}
}

/*UpdateAppTagsUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateAppTagsUnauthorized struct {
}

func (o *UpdateAppTagsUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTagsUnauthorized ", 401)
}

func (o *UpdateAppTagsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAppTagsForbidden creates a UpdateAppTagsForbidden with default headers values
func NewUpdateAppTagsForbidden() *UpdateAppTagsForbidden {
	return &UpdateAppTagsForbidden{}
}

/*UpdateAppTagsForbidden handles this case with default header values.

Forbidden
*/
type UpdateAppTagsForbidden struct {
}

func (o *UpdateAppTagsForbidden) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTagsForbidden ", 403)
}

func (o *UpdateAppTagsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAppTagsUnprocessableEntity creates a UpdateAppTagsUnprocessableEntity with default headers values
func NewUpdateAppTagsUnprocessableEntity() *UpdateAppTagsUnprocessableEntity {
	return &UpdateAppTagsUnprocessableEntity{}
}

/*UpdateAppTagsUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type UpdateAppTagsUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

func (o *UpdateAppTagsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTagsUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateAppTagsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppTagsTooManyRequests creates a UpdateAppTagsTooManyRequests with default headers values
func NewUpdateAppTagsTooManyRequests() *UpdateAppTagsTooManyRequests {
	return &UpdateAppTagsTooManyRequests{}
}

/*UpdateAppTagsTooManyRequests handles this case with default header values.

Too many requests
*/
type UpdateAppTagsTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *UpdateAppTagsTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTagsTooManyRequests  %+v", 429, o.Payload)
}

func (o *UpdateAppTagsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppTagsDefault creates a UpdateAppTagsDefault with default headers values
func NewUpdateAppTagsDefault(code int) *UpdateAppTagsDefault {
	return &UpdateAppTagsDefault{
		_statusCode: code,
	}
}

/*UpdateAppTagsDefault handles this case with default header values.

Unexpected error
*/
type UpdateAppTagsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the update app tags default response
func (o *UpdateAppTagsDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAppTagsDefault) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/tags][%d] updateAppTags default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAppTagsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
