// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// UpdateAppSettingsReader is a Reader for the UpdateAppSettings structure.
type UpdateAppSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAppSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateAppSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateAppSettingsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewUpdateAppSettingsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewUpdateAppSettingsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewUpdateAppSettingsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewUpdateAppSettingsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewUpdateAppSettingsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAppSettingsOK creates a UpdateAppSettingsOK with default headers values
func NewUpdateAppSettingsOK() *UpdateAppSettingsOK {
	return &UpdateAppSettingsOK{}
}

/*UpdateAppSettingsOK handles this case with default header values.

An app settings model.
*/
type UpdateAppSettingsOK struct {
	Payload *models.UpdateAppSettingsResponse
}

func (o *UpdateAppSettingsOK) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettingsOK  %+v", 200, o.Payload)
}

func (o *UpdateAppSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateAppSettingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppSettingsBadRequest creates a UpdateAppSettingsBadRequest with default headers values
func NewUpdateAppSettingsBadRequest() *UpdateAppSettingsBadRequest {
	return &UpdateAppSettingsBadRequest{}
}

/*UpdateAppSettingsBadRequest handles this case with default header values.

Bad request
*/
type UpdateAppSettingsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *UpdateAppSettingsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettingsBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateAppSettingsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppSettingsUnauthorized creates a UpdateAppSettingsUnauthorized with default headers values
func NewUpdateAppSettingsUnauthorized() *UpdateAppSettingsUnauthorized {
	return &UpdateAppSettingsUnauthorized{}
}

/*UpdateAppSettingsUnauthorized handles this case with default header values.

Not authenticated
*/
type UpdateAppSettingsUnauthorized struct {
}

func (o *UpdateAppSettingsUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettingsUnauthorized ", 401)
}

func (o *UpdateAppSettingsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAppSettingsForbidden creates a UpdateAppSettingsForbidden with default headers values
func NewUpdateAppSettingsForbidden() *UpdateAppSettingsForbidden {
	return &UpdateAppSettingsForbidden{}
}

/*UpdateAppSettingsForbidden handles this case with default header values.

Not authorized
*/
type UpdateAppSettingsForbidden struct {
}

func (o *UpdateAppSettingsForbidden) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettingsForbidden ", 403)
}

func (o *UpdateAppSettingsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAppSettingsUnprocessableEntity creates a UpdateAppSettingsUnprocessableEntity with default headers values
func NewUpdateAppSettingsUnprocessableEntity() *UpdateAppSettingsUnprocessableEntity {
	return &UpdateAppSettingsUnprocessableEntity{}
}

/*UpdateAppSettingsUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type UpdateAppSettingsUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

func (o *UpdateAppSettingsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettingsUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateAppSettingsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppSettingsTooManyRequests creates a UpdateAppSettingsTooManyRequests with default headers values
func NewUpdateAppSettingsTooManyRequests() *UpdateAppSettingsTooManyRequests {
	return &UpdateAppSettingsTooManyRequests{}
}

/*UpdateAppSettingsTooManyRequests handles this case with default header values.

Too many requests
*/
type UpdateAppSettingsTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *UpdateAppSettingsTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettingsTooManyRequests  %+v", 429, o.Payload)
}

func (o *UpdateAppSettingsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAppSettingsDefault creates a UpdateAppSettingsDefault with default headers values
func NewUpdateAppSettingsDefault(code int) *UpdateAppSettingsDefault {
	return &UpdateAppSettingsDefault{
		_statusCode: code,
	}
}

/*UpdateAppSettingsDefault handles this case with default header values.

Unexpected error
*/
type UpdateAppSettingsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the update app settings default response
func (o *UpdateAppSettingsDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAppSettingsDefault) Error() string {
	return fmt.Sprintf("[PUT /apps/{appNameOrId}/settings][%d] updateAppSettings default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAppSettingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
