// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSchedulesParams creates a new DeleteSchedulesParams object
// with the default values initialized.
func NewDeleteSchedulesParams() *DeleteSchedulesParams {
	var ()
	return &DeleteSchedulesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSchedulesParamsWithTimeout creates a new DeleteSchedulesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSchedulesParamsWithTimeout(timeout time.Duration) *DeleteSchedulesParams {
	var ()
	return &DeleteSchedulesParams{

		timeout: timeout,
	}
}

// NewDeleteSchedulesParamsWithContext creates a new DeleteSchedulesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSchedulesParamsWithContext(ctx context.Context) *DeleteSchedulesParams {
	var ()
	return &DeleteSchedulesParams{

		Context: ctx,
	}
}

// NewDeleteSchedulesParamsWithHTTPClient creates a new DeleteSchedulesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSchedulesParamsWithHTTPClient(client *http.Client) *DeleteSchedulesParams {
	var ()
	return &DeleteSchedulesParams{
		HTTPClient: client,
	}
}

/*DeleteSchedulesParams contains all the parameters to send to the API endpoint
for the delete schedules operation typically these are written to a http.Request
*/
type DeleteSchedulesParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*InstalledAppID
	  The ID of the installed application.

	*/
	InstalledAppID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete schedules params
func (o *DeleteSchedulesParams) WithTimeout(timeout time.Duration) *DeleteSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete schedules params
func (o *DeleteSchedulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete schedules params
func (o *DeleteSchedulesParams) WithContext(ctx context.Context) *DeleteSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete schedules params
func (o *DeleteSchedulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete schedules params
func (o *DeleteSchedulesParams) WithHTTPClient(client *http.Client) *DeleteSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete schedules params
func (o *DeleteSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete schedules params
func (o *DeleteSchedulesParams) WithAuthorization(authorization string) *DeleteSchedulesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete schedules params
func (o *DeleteSchedulesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstalledAppID adds the installedAppID to the delete schedules params
func (o *DeleteSchedulesParams) WithInstalledAppID(installedAppID string) *DeleteSchedulesParams {
	o.SetInstalledAppID(installedAppID)
	return o
}

// SetInstalledAppID adds the installedAppId to the delete schedules params
func (o *DeleteSchedulesParams) SetInstalledAppID(installedAppID string) {
	o.InstalledAppID = installedAppID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param installedAppId
	if err := r.SetPathParam("installedAppId", o.InstalledAppID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
