// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetScheduleParams creates a new GetScheduleParams object
// with the default values initialized.
func NewGetScheduleParams() *GetScheduleParams {
	var ()
	return &GetScheduleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScheduleParamsWithTimeout creates a new GetScheduleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScheduleParamsWithTimeout(timeout time.Duration) *GetScheduleParams {
	var ()
	return &GetScheduleParams{

		timeout: timeout,
	}
}

// NewGetScheduleParamsWithContext creates a new GetScheduleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScheduleParamsWithContext(ctx context.Context) *GetScheduleParams {
	var ()
	return &GetScheduleParams{

		Context: ctx,
	}
}

// NewGetScheduleParamsWithHTTPClient creates a new GetScheduleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScheduleParamsWithHTTPClient(client *http.Client) *GetScheduleParams {
	var ()
	return &GetScheduleParams{
		HTTPClient: client,
	}
}

/*GetScheduleParams contains all the parameters to send to the API endpoint
for the get schedule operation typically these are written to a http.Request
*/
type GetScheduleParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*InstalledAppID
	  The ID of the installed application.

	*/
	InstalledAppID string
	/*ScheduleName
	  The name of the schedule

	*/
	ScheduleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get schedule params
func (o *GetScheduleParams) WithTimeout(timeout time.Duration) *GetScheduleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schedule params
func (o *GetScheduleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schedule params
func (o *GetScheduleParams) WithContext(ctx context.Context) *GetScheduleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schedule params
func (o *GetScheduleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schedule params
func (o *GetScheduleParams) WithHTTPClient(client *http.Client) *GetScheduleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schedule params
func (o *GetScheduleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get schedule params
func (o *GetScheduleParams) WithAuthorization(authorization string) *GetScheduleParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get schedule params
func (o *GetScheduleParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstalledAppID adds the installedAppID to the get schedule params
func (o *GetScheduleParams) WithInstalledAppID(installedAppID string) *GetScheduleParams {
	o.SetInstalledAppID(installedAppID)
	return o
}

// SetInstalledAppID adds the installedAppId to the get schedule params
func (o *GetScheduleParams) SetInstalledAppID(installedAppID string) {
	o.InstalledAppID = installedAppID
}

// WithScheduleName adds the scheduleName to the get schedule params
func (o *GetScheduleParams) WithScheduleName(scheduleName string) *GetScheduleParams {
	o.SetScheduleName(scheduleName)
	return o
}

// SetScheduleName adds the scheduleName to the get schedule params
func (o *GetScheduleParams) SetScheduleName(scheduleName string) {
	o.ScheduleName = scheduleName
}

// WriteToRequest writes these params to a swagger request
func (o *GetScheduleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param installedAppId
	if err := r.SetPathParam("installedAppId", o.InstalledAppID); err != nil {
		return err
	}

	// path param scheduleName
	if err := r.SetPathParam("scheduleName", o.ScheduleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
