// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSchedulesParams creates a new GetSchedulesParams object
// with the default values initialized.
func NewGetSchedulesParams() *GetSchedulesParams {
	var ()
	return &GetSchedulesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchedulesParamsWithTimeout creates a new GetSchedulesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSchedulesParamsWithTimeout(timeout time.Duration) *GetSchedulesParams {
	var ()
	return &GetSchedulesParams{

		timeout: timeout,
	}
}

// NewGetSchedulesParamsWithContext creates a new GetSchedulesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSchedulesParamsWithContext(ctx context.Context) *GetSchedulesParams {
	var ()
	return &GetSchedulesParams{

		Context: ctx,
	}
}

// NewGetSchedulesParamsWithHTTPClient creates a new GetSchedulesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSchedulesParamsWithHTTPClient(client *http.Client) *GetSchedulesParams {
	var ()
	return &GetSchedulesParams{
		HTTPClient: client,
	}
}

/*GetSchedulesParams contains all the parameters to send to the API endpoint
for the get schedules operation typically these are written to a http.Request
*/
type GetSchedulesParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*InstalledAppID
	  The ID of the installed application.

	*/
	InstalledAppID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get schedules params
func (o *GetSchedulesParams) WithTimeout(timeout time.Duration) *GetSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schedules params
func (o *GetSchedulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schedules params
func (o *GetSchedulesParams) WithContext(ctx context.Context) *GetSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schedules params
func (o *GetSchedulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schedules params
func (o *GetSchedulesParams) WithHTTPClient(client *http.Client) *GetSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schedules params
func (o *GetSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get schedules params
func (o *GetSchedulesParams) WithAuthorization(authorization string) *GetSchedulesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get schedules params
func (o *GetSchedulesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstalledAppID adds the installedAppID to the get schedules params
func (o *GetSchedulesParams) WithInstalledAppID(installedAppID string) *GetSchedulesParams {
	o.SetInstalledAppID(installedAppID)
	return o
}

// SetInstalledAppID adds the installedAppId to the get schedules params
func (o *GetSchedulesParams) SetInstalledAppID(installedAppID string) {
	o.InstalledAppID = installedAppID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param installedAppId
	if err := r.SetPathParam("installedAppId", o.InstalledAppID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
