// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeviceComponentStatusParams creates a new GetDeviceComponentStatusParams object
// with the default values initialized.
func NewGetDeviceComponentStatusParams() *GetDeviceComponentStatusParams {
	var ()
	return &GetDeviceComponentStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeviceComponentStatusParamsWithTimeout creates a new GetDeviceComponentStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeviceComponentStatusParamsWithTimeout(timeout time.Duration) *GetDeviceComponentStatusParams {
	var ()
	return &GetDeviceComponentStatusParams{

		timeout: timeout,
	}
}

// NewGetDeviceComponentStatusParamsWithContext creates a new GetDeviceComponentStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeviceComponentStatusParamsWithContext(ctx context.Context) *GetDeviceComponentStatusParams {
	var ()
	return &GetDeviceComponentStatusParams{

		Context: ctx,
	}
}

// NewGetDeviceComponentStatusParamsWithHTTPClient creates a new GetDeviceComponentStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeviceComponentStatusParamsWithHTTPClient(client *http.Client) *GetDeviceComponentStatusParams {
	var ()
	return &GetDeviceComponentStatusParams{
		HTTPClient: client,
	}
}

/*GetDeviceComponentStatusParams contains all the parameters to send to the API endpoint
for the get device component status operation typically these are written to a http.Request
*/
type GetDeviceComponentStatusParams struct {

	/*Authorization
	  OAuth token

	*/
	Authorization string
	/*ComponentID
	  The name of the component.

	*/
	ComponentID string
	/*DeviceID
	  the device ID

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get device component status params
func (o *GetDeviceComponentStatusParams) WithTimeout(timeout time.Duration) *GetDeviceComponentStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device component status params
func (o *GetDeviceComponentStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get device component status params
func (o *GetDeviceComponentStatusParams) WithContext(ctx context.Context) *GetDeviceComponentStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device component status params
func (o *GetDeviceComponentStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get device component status params
func (o *GetDeviceComponentStatusParams) WithHTTPClient(client *http.Client) *GetDeviceComponentStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device component status params
func (o *GetDeviceComponentStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get device component status params
func (o *GetDeviceComponentStatusParams) WithAuthorization(authorization string) *GetDeviceComponentStatusParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get device component status params
func (o *GetDeviceComponentStatusParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithComponentID adds the componentID to the get device component status params
func (o *GetDeviceComponentStatusParams) WithComponentID(componentID string) *GetDeviceComponentStatusParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the get device component status params
func (o *GetDeviceComponentStatusParams) SetComponentID(componentID string) {
	o.ComponentID = componentID
}

// WithDeviceID adds the deviceID to the get device component status params
func (o *GetDeviceComponentStatusParams) WithDeviceID(deviceID string) *GetDeviceComponentStatusParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the get device component status params
func (o *GetDeviceComponentStatusParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeviceComponentStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param componentId
	if err := r.SetPathParam("componentId", o.ComponentID); err != nil {
		return err
	}

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
