// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/SmartThingsOSS/smartapp-go/pkg/smartthings/models"
)

// InstallDeviceReader is a Reader for the InstallDevice structure.
type InstallDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstallDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInstallDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewInstallDeviceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewInstallDeviceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewInstallDeviceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewInstallDeviceUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewInstallDeviceTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewInstallDeviceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInstallDeviceOK creates a InstallDeviceOK with default headers values
func NewInstallDeviceOK() *InstallDeviceOK {
	return &InstallDeviceOK{}
}

/*InstallDeviceOK handles this case with default header values.

Device Installed.
*/
type InstallDeviceOK struct {
	Payload *models.Device
}

func (o *InstallDeviceOK) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDeviceOK  %+v", 200, o.Payload)
}

func (o *InstallDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Device)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstallDeviceBadRequest creates a InstallDeviceBadRequest with default headers values
func NewInstallDeviceBadRequest() *InstallDeviceBadRequest {
	return &InstallDeviceBadRequest{}
}

/*InstallDeviceBadRequest handles this case with default header values.

Bad request
*/
type InstallDeviceBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *InstallDeviceBadRequest) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDeviceBadRequest  %+v", 400, o.Payload)
}

func (o *InstallDeviceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstallDeviceUnauthorized creates a InstallDeviceUnauthorized with default headers values
func NewInstallDeviceUnauthorized() *InstallDeviceUnauthorized {
	return &InstallDeviceUnauthorized{}
}

/*InstallDeviceUnauthorized handles this case with default header values.

Not authenticated
*/
type InstallDeviceUnauthorized struct {
}

func (o *InstallDeviceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDeviceUnauthorized ", 401)
}

func (o *InstallDeviceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstallDeviceForbidden creates a InstallDeviceForbidden with default headers values
func NewInstallDeviceForbidden() *InstallDeviceForbidden {
	return &InstallDeviceForbidden{}
}

/*InstallDeviceForbidden handles this case with default header values.

Not authorized
*/
type InstallDeviceForbidden struct {
}

func (o *InstallDeviceForbidden) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDeviceForbidden ", 403)
}

func (o *InstallDeviceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstallDeviceUnprocessableEntity creates a InstallDeviceUnprocessableEntity with default headers values
func NewInstallDeviceUnprocessableEntity() *InstallDeviceUnprocessableEntity {
	return &InstallDeviceUnprocessableEntity{}
}

/*InstallDeviceUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type InstallDeviceUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

func (o *InstallDeviceUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDeviceUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *InstallDeviceUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstallDeviceTooManyRequests creates a InstallDeviceTooManyRequests with default headers values
func NewInstallDeviceTooManyRequests() *InstallDeviceTooManyRequests {
	return &InstallDeviceTooManyRequests{}
}

/*InstallDeviceTooManyRequests handles this case with default header values.

Too many requests
*/
type InstallDeviceTooManyRequests struct {
	Payload *models.ErrorResponse
}

func (o *InstallDeviceTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDeviceTooManyRequests  %+v", 429, o.Payload)
}

func (o *InstallDeviceTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstallDeviceDefault creates a InstallDeviceDefault with default headers values
func NewInstallDeviceDefault(code int) *InstallDeviceDefault {
	return &InstallDeviceDefault{
		_statusCode: code,
	}
}

/*InstallDeviceDefault handles this case with default header values.

Unexpected error
*/
type InstallDeviceDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the install device default response
func (o *InstallDeviceDefault) Code() int {
	return o._statusCode
}

func (o *InstallDeviceDefault) Error() string {
	return fmt.Sprintf("[POST /devices][%d] installDevice default  %+v", o._statusCode, o.Payload)
}

func (o *InstallDeviceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
